kind: Service
apiVersion: v1
metadata:
  name: pesbuk-service
  namespace: staging
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: php-pesbuk

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-deployment
  namespace: staging
  labels:
    app: php-pesbuk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-pesbuk
      track: stable
  template:
    metadata:
      labels:
        app: php-pesbuk
        track: stable
    spec:
      containers:
      - name: php-pesbuk
        image: 25092018/sosial-media:macross
        ports:
        - containerPort: 80
        env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pb-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pb-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pb-secret
                  key: password

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pesbuk-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: stagingsosmed.rizdin.online
    http:
      paths:
      #- path: /
      - backend:
          serviceName: pesbuk-service
          servicePort: 80
