kind: Service
apiVersion: v1
metadata:
  name: sosmed-service
  namespace: staging
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: php-pesbuk

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosmed-deployment
  namespace: staging
  labels:
    app: php-pesbuk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-pesbuk
      track: stable
  template:
    metadata:
      labels:
        app: php-pesbuk
        track: stable
    spec:
      containers:
      - name: php-pesbuk
        image: 25092018/stgsosial-media:@
        ports:
        - containerPort: 80
        env:
            - name: pb_db_host
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: pb_host
            - name: pb_db_user
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: pb_user
            - name: pb_db_pass
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: pb_pass
            - name: pb_db_name
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: pb_name

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sosmed-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: stgsosmed.rizdin.online
    http:
      paths:
      #- path: /
      - backend:
          serviceName: sosmed-service
          servicePort: 80
